version = 1.0.0-alpha.72
kotlinVersion=2.4.10
postgresPort=5432
schema=pace
springBootVersion=4.1.1
jooqVersion=3.18.7
kotestVersion = 6.2.4
springCloudKubernetesVersion=5.0.3
flywayVersion=13.5.0
protobufJavaUtilVersion=4.36.1

dockertag = pace-local

generatedBufDependencyVersion=00000000000000.a3f0157251ce
