{#
    This file was auto-generated by PACE. Do not edit this file directly.
#}
{{
    config(
      materialized='view',
      meta={'pace_generated': true}
    )
}}

select
  transactionid,
  case
    when (is_account_group_member('administrator')) then userid
    else null
  end userid,
  case
    when (is_account_group_member('administrator')) then email
    else regexp_replace('email', '^.*(@.*)$', '****$1')
  end email,
  age,
  transactionamount,
  brand
from {{ ref('stg_demo') }}
where case
  when (is_account_group_member('administrator')) then true
  else age > 18
end
