{#
    This file was auto-generated by PACE. Do not edit this file directly.
#}
{{
    config(
      materialized='view'
    )
}}

with
  user_groups as (
    select userGroup
    from `stream-machine-development.user_groups.user_groups`
    where userEmail = SESSION_USER()
  )
select case
  when (
    ('fraud_and_risk' IN ( SELECT `userGroup` FROM `user_groups` ))
    or ('administrator' IN ( SELECT `userGroup` FROM `user_groups` ))
  ) then `id`
  else 42
end `id`
from {{ ref('my_second_dbt_model') }}
