spring:
  datasource:
    url: jdbc:postgresql://postgres_pace:5432/pace
    hikari:
      username: pace
      password: pace
      schema: public

app:
  plugins:
    openai:
      enabled: true
      apiKey: "put your OpenAI api-key here"
      # use a gpt-4 model to follow along with the documentation
      model: "gpt-4-1106-preview"
