spring:
  datasource:
    url: jdbc:postgresql://localhost:5439/pace
    hikari:
      username: pace
      password: pace
      schema: public

logging:
  level:
    com.getstrm.pace.snowflake.SnowflakeJwtIssuer: DEBUG

app:
  plugins:
    openai:
      enabled: true
      apiKey: "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"
      model: "gpt-4-1106-preview"
      timeout: 120
  processing-platforms:
    # postgres:
    #   - id: "paceso"
    #     host-name: "localhost"
    #     port: 5439
    #     user-name: "paceso"
    #     password: "paceso"
    #     database: "paceso"
    bigquery:
      - id: "bigquery-dev"
        project-id: "stream-machine-development"
        user-groups-table: "stream-machine-development.user_groups.user_groups"
        service-account-json-key: |
          {
            "type": "service_account",
            "project_id": "stream-machine-development",
            "private_key_id": "063e6b77eddafd1c3c9b1348b5173cecf3fa174f",
            "private_key": "-----BEGIN PRIVATE KEY-----\nMIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQDeUGjOmr5h7grg\n+YGBf4iSyKBLKhKikepKiAGAfz90e+H3XAqes1VxwGAlYsLktC46GCo7FyZUX7T0\npc0dUjBwh4vATUdjXFO3SG6FDikpIGEQ25pOMcLBA3huBMMU8nyPtHfKOFJpWXZZ\npLOAz6yc0/f+zcz7JsP3KFzOxPh2zZtPM1IFRP0BaAJCzv0kywSnN5TOyJK+H63e\n29Jgyf0emw4JO/ggdkysYh6EuyH44V9tkelVOKSLIFJ32FOQDTJhTxmmFbJIg6qw\naJygNnUt8a5IzRyqd9ZbPr+O6reZhFeexhjABvuu7B0X7Z7qyBiamLhMaW/dlmJX\nJ/F26W8xAgMBAAECggEACTOJyvdTpuj70UjyZ8I4DF86ZzIEGG9yo4gSi9d4cGFK\nPns0Q1JH2I/uSs3WJDIi8aubX9u67eYSLsgH/80tjRLHIXvxVvb0zhK05FPsNzQM\nYG6+abschPGYU/Flg6HvruD4zklbe9nEkLxE47F0wv7w9j5dXA3EMaAdiz9Sy1Pu\nbXhisnSsHsTCPxB+JNKMRSXZ55mdRRWt4Msqgt1EhTAhHkaCLrSNoZGp8PoZOQEZ\nMjSzCIetXCJHDlp0Cs11Dd1clC22iTagY/MalihdkyfdM4FSBmFv+EbHg9heC/Y5\nXmiC3P/HYVEVqo9NyLjTDmBFT3hylaNlA8sYpN/WGwKBgQD+/uow1fw+dSkIcEoz\nKzO55XFsZiS6up4DHfHLOJdGh017ILgV0W8+sZX4m54nMaolMiXhF6goAzam2XX6\nINxNOSUBY2wZjbtDGl8jVP7NHJ6LtmfF3OjzpaX+XtJJ8+MiwGOPjK/JmX63HpL8\nG0Q9+RHfmpKhtRTvPhdJXTtvWwKBgQDfMIuOTO5ezprmBQkWTAMQFSU9FQT4jicF\nQ7e+MzbISoMy40PmWMX/GoccFP7ChO6hyHrHnf+sijZJjDcua8sfQ2aAfzm9EnHN\nmfRIVY5qP4dK1hwlbKK4E9tPi48GOZazChfbf0ETTrfRIGHSzKBUdDHLXVi2FXF8\nPB2vy31NYwKBgQDfLB+vajkAOO4WsqBeNDtrQYKJisQuoVHWDIkogXj0g0qurq4u\nekRQrIBDO3+pcfAl6cP5QwkrK9TTJpP4vHXTKGZY1rkvjDoOuq/1blgrEBc61APy\nyisfwySKglat3sQ2EAeTBWB8otiiUCH4f6y0SJ76AoC/Aos18DPVQ8HW7QKBgEmx\nVrLyldY58401Zm21RWGfCb+kXBLRpPKpDFdBw7nYWH+J6JZ7A00a7jeIeyGxELXc\nYyXb9lp6/DfGk0XBk7zL3WFaIK9cErVnOvBTR4WvWjWMgpicyRFshQI7u0q74xVU\npNH1r3/3gtwLDCG1LM8V2ociWDMu21zA4LB1yPavAoGARV1pg7Y8kQwYFflTWj2v\nUZ+7HarAy8KHLss1yUpbZJF2y0ReWwBun9yy6wJ6HwzbbCywHktuvD6pTD9wh3tE\nU7cG9rsprI5fzvaRVpfOYV1UPkG6HeO7+FYTfALcG6cDpPowrirPmCy4YDuPQs0i\nY4Od038EfZPyu8jBCtBAuSk=\n-----END PRIVATE KEY-----\n",
            "client_email": "dps-bigquery-poc@stream-machine-development.iam.gserviceaccount.com",
            "client_id": "104066739856134154650",
            "auth_uri": "https://accounts.google.com/o/oauth2/auth",
            "token_uri": "https://oauth2.googleapis.com/token",
            "auth_provider_x509_cert_url": "https://www.googleapis.com/oauth2/v1/certs",
            "client_x509_cert_url": "https://www.googleapis.com/robot/v1/metadata/x509/dps-bigquery-poc%40stream-machine-development.iam.gserviceaccount.com",
            "universe_domain": "googleapis.com"
          }
#    databricks:
#      - id: "dbr-pace"
#        workspaceHost: "https://dbc-727bc7c4-fac4.cloud.databricks.com/"
#        accountHost: "https://accounts.cloud.databricks.com"
#        accountId: "4ca01e49-1f59-41a0-a4c4-389b4bb792b7"
#        clientId: "87764673-c41e-494b-8dd1-1f3336740a7d"
#        clientSecret: "dosed0a208e888fafda22648402f0baa810a"
#        warehouseId: "3bd5bad2faebe512"
#    snowflake:
#      - id: "sf-pace"
#        serverUrl: "https://xd30863.eu-central-1.snowflakecomputing.com"
#        database: "PACE"
#        warehouse: "COMPUTE_WH"
#        userName: "pace_user"
#        accountName: "MV79218"
#        organizationName: "SPMXIFV"
#        privateKey: |
#          -----BEGIN PRIVATE KEY-----
#          MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQC7i22m1G+//p+F
#          /fHNRBZCajDUfq+iG5e9nS6HU2Hk+DmmSXIK0MARb3GNb3dgeZAbqfg94GdrFZCX
#          qhC3i/V5MPDBkXHWaIE+XOE/D8nn2k/PWhyoodTYph3Sfp8d06nnCaUF4LV7/n7H
#          L8goSaLTQavJdBbxgWjymaMZ37Zhl1t2hX9xTcm6V/4uOaMiav8E8akn5H7SQfG0
#          z3yflKbcJxZ0DtvOW/jHnXEMWFoWwKoKhbaKc61ZO29e9km18Ked9kDLC0k5zn7t
#          BmNNWYgdDMSakuR5AQ4ldlxCQ9f8M/hGmgDefyOOikhbJiEe3X+A9ZBFgkeofjCt
#          u+b/Z30VAgMBAAECggEAVHOvP2JHJi5bGGPnqFbCLUsTTQT1Quro9CYdJywZl5ld
#          oG9PTuZ8rv0/pYBtwcBL7+Ekm3x7JYHy+BDJcVWxhs7Og2Pi3rl1haceeR67fU/W
#          A5ng8ODa72oyYLDLJwvC5Pp3WMO9BaZu4XQ3TkkGbNoUKOXBVSRApYogo4yVXLEd
#          UMnkxgPWqpHRykVwlarF39oz83CtG0yxd+0sUUdsV3ct/T4VHQF5fBrIaGZe5QvJ
#          jAgGaBzj5KMbxfIBxJHJPr5htdzulAOlAVTA0Q2UiGMpaby5JyJD7rq/rKDbHEe2
#          y6WVTi2oExpTnAytkiHXqP02fS+xq0c7urzhZBk4GwKBgQDrgaA8sGOfjqxDjwOj
#          ZzQQPc32dVOR7hMbkWSyHDsPza565qlgnXqKffCsbQtKqWOVlaDbbwgpLNaQ/Hfl
#          zJe8sCg0wB52lF9vm4u0NaWG11Endr6SVhiALsktEwoSRps8QDfiO4tL2SWonBqS
#          ZVkWbbfGv8Kdlah1tPcBSteTJwKBgQDL3VwN54qqJuDTzJKbEPAktyJYtMXPPwQp
#          835BNTUMHd5Kn5urEunZffD2k96tjpKZ7f/MuBfqOa73v66uCh130SJfgeVR4Hd+
#          5lDFe75iJEpoa8nIPNvw7XigNyL6TnhocTLmZZ1nC47+QKq+Z/sxfoVjLR5uXMB6
#          QVkyZcLjYwKBgQDnti1TKPWMCpNBEVgyEJuwEy8ve3aTERvptt7NQ2t0/BjcwVAL
#          SEZGNu1yqQNAHXNmvMZ8wDzWTlB6bH0HM4pj0ypr5E7Uut0/cVo+H75R8k3dtz5/
#          uof2rpGvcJkrLB8WY9TYGV/Pa8Jap+SY/3Bs2dzEhu3ToGkUDs4sjleWZwKBgGF7
#          hgs4DrxyPsvIZMo1fT9xOsFEH9qL/Ye54UN5F9alaagxThStxJi1ekXOS4qeREfK
#          4KiZ1wWvc5UQWYzrVU/39wHIcUmHllxd8X2dQFpZlCL+d8yCHYHFbArgkp8yaq02
#          g+pb6Lpfco7tiTfnLNxr7YiRCJ4pR/ityuMoedqVAoGAAiHIr2vzx2spqQoA5Gl8
#          4bPa1MzC/XaDpZl5QIwvPgwfvYGuhMxN2D+/OsH70OOmMSprSOqYvPfjwL39lAIO
#          7XCdlMBkJyv2MVEvYOemmxnmczFVImH9JVKcmKnSv/Kc9U+WC9tS8lmuYfOGmikk
#          8jc6F8x+R03amdLQ4dCCOWs=
#          -----END PRIVATE KEY-----
  catalogs:
    - id: "collibra"
      type: "COLLIBRA"
      serverUrl: "https://getstrm.collibra.com/graphql/knowledgeGraph/v1"
      userName: "Admin"
      password: "wyj!CPM8nmh_uax4ceb"
    # - id: "datahub"
    #   type: "DATAHUB"
    #   serverUrl: "http://localhost:9002/api/graphql"
    #   fetchSize: 1
    #   token: "eyJhbGciOiJIUzI1NiJ9.eyJhY3RvclR5cGUiOiJVU0VSIiwiYWN0b3JJZCI6ImRhdGFodWIiLCJ0eXBlIjoiUEVSU09OQUwiLCJ2ZXJzaW9uIjoiMiIsImp0aSI6IjFjMmI2ZDcwLWQ0OGMtNGJiZS04YTI4LTYwNDMyZjBkMjI3NSIsInN1YiI6ImRhdGFodWIiLCJleHAiOjE3MTM5NzA0ODMsImlzcyI6ImRhdGFodWItbWV0YWRhdGEtc2VydmljZSJ9.rDH380TsRRewa_w1J4c0TQCH8U2GFOebNZ9PnkR2NNk"
    # - id: odd
    #   type: ODD
    #   serverUrl: http://localhost:8087
server:
  port: 8085
