
version: 2

models:
  - name: my_first_dbt_model
    description: "A starter dbt model"
    columns:
      - name: id
        description: "The primary key for this table"
        tests:
          - unique
          - not_null
        tags:
          - banaan

  - name: my_second_dbt_model
    description: "A starter dbt model"
    columns:
      - name: id
        description: "The primary key for this table"
        tests:
          - unique
          - not_null

  - name: stg_demo
    columns:
      - name: transactionid
      - name: userid
      - name: email
      - name: age
      - name: transactionamount
      - name: brand
    meta:
      pace:
        rule_sets:
          - target:
              ref:
                integration_fqn: public.demo_view
              filters:
                - generic_filter:
                    conditions:
                      - principals: [ { group: administrator }, { group: fraud_and_risk } ]
                        condition: "true"
                      - principals: [ ]
                        condition: "age > 8"
              field_transforms:
                - field:
                    name_parts: [ userid ]
                    transforms:
                      - principals: [ { group: fraud_and_risk }, { group: administrator } ]
                        identity: { }
                      - principals: [ ]
                        fixed:
                          value: "0000"
                - field:
                    name_parts: [ email ]
                    transforms:
                      - principals: [ { group: administrator } ]
                        identity: { }
