
version: 2

models:
  - name: my_first_dbt_model
    description: "A starter dbt model"
    columns:
      - name: id
        description: "The primary key for this table"
        tests:
          - unique
          - not_null
        tags:
          - banaan

  - name: my_second_dbt_model
    description: "A starter dbt model"
    columns:
      - name: id
        description: "The primary key for this table"
        tests:
          - unique
          - not_null

  - name: stg_demo
    columns:
      - name: transactionid
      - name: userid
        meta:
          pace:
            transforms:
              - principals: [ { group: fraud_and_risk }, { group: administrator } ]
                identity: { }
              - principals: [ ]
                fixed:
                  value: "42"
      - name: email
        meta:
          pace:
            transforms:
              - principals: [ { group: administrator } ]
                identity: { }
              - principals: [ ]
                fixed:
                  # this must be quoted if the data types of the model are absent
                  # because we fall back to implicit types in that case
                  value: "'banaan@banaan.com'"
      - name: age
      - name: transactionamount
      - name: brand
    meta:
      pace:
        rule_sets:
          - target:
              ref:
                integration_fqn: public.banaan
            filters:
              - generic_filter:
                  conditions:
                    - principals: [ { group: administrator }, { group: fraud_and_risk } ]
                      condition: "true"
                    - principals: [ ]
                      condition: "age > 8"
