spring:
  datasource:
    url: jdbc:postgresql://postgres_pace:5432/pace
    hikari:
      username: pace
      password: pace
      schema: public

app:
  processing-platforms:
    postgres:
      - id: "numeric-rounding-connection"
        host-name: "postgres_processing_platform"
        port: 5432
        user-name: "numeric_rounding"
        password: "numeric_rounding"
        database: "numeric_rounding"

