mysqlSetupJob:
  enabled: false

postgresqlSetupJob:
  enabled: true

## No code data migration
datahubUpgrade:
  noCodeDataMigration:
    sqlDbType: "POSTGRES"

global:
  sql:
    datasource:
       host: "prerequisites-postgresql:5432"
       hostForpostgresqlClient: "prerequisites-postgresql"
       port: "5432"
       url: "jdbc:postgresql://prerequisites-postgresql:5432/datahub"
       driver: "org.postgresql.Driver"
       username: "postgres"
       password:
         secretRef: prerequisites-postgresql
         secretKey: postgres-password

  datahub:
    metadata_service_authentication:
      enabled: true
