spring:
  datasource:
    url: jdbc:postgresql://postgres_pace:5432/pace
    hikari:
      username: pace
      password: pace
      schema: public
app:
  expose-application-exceptions: true
  processing-platforms:
    bigquery:
      - id: "bigquery-pp"
        project-id: <-- your project id here -->
        use-iam-check-extension: true
        service-account-json-key: |
          <-- your service account json key here -->