{#
    This file was auto-generated by PACE. Do not edit this file directly.
#}
{{
    config(
      materialized='view',
      database='pace',
      schema='online_retail'
    )
}}

select
  COUNTRY,
  case
    when (IS_ROLE_IN_SESSION('ACCOUNTADMIN')) then CUSTOMERID
    else null
  end CUSTOMERID,
  DESCRIPTION,
  INVOICE,
  INVOICEDATE,
  PRICE,
  QUANTITY,
  STOCKCODE
from {{ ref('retail_2010') }}
where case
  when (
    (IS_ROLE_IN_SESSION('ACCOUNTADMIN'))
    or (IS_ROLE_IN_SESSION('FRAUD_AND_RISK'))
  ) then true
  else COUNTRY like 'Germany'
end
