spring:
  datasource:
    url: jdbc:postgresql://postgres_pace:5432/pace
    hikari:
      username: pace
      password: pace
      schema: public

app:
  plugins:
    openai:
      enabled: true
      api-key: "put-your-api-key-here"
      # default model, or use the gpt-4-1106-preview model if you have access
      model: "gpt-4-1106-preview"
