spring:
  datasource:
    url: jdbc:postgresql://postgres_pace:5432/pace
    hikari:
      username: pace
      password: pace
      schema: public

app:
  processing-platforms:
    postgres:
      - id: "standalone-sample-connection"
        host-name: "postgres_processing_platform"
        port: 5432
        user-name: "standalone"
        password: "standalone"
        database: "standalone"

  plugins:
    openai:
      enabled: true
      api-key: "put-your-api-key-here"
      # default model, or use the gpt-4-1106-preview model if you have access
      model: "gpt-4-1106-preview"
