name: Docs

on:
  push:
    branches:
      - alpha # change this to the branch we're actively working on, as Gitbook can only sync from a single branch
    paths-ignore:
      - "docs/**"

jobs:
  publish_docs:
    runs-on: ubuntu-latest
    if: "contains(github.event.head_commit.message, 'chore(release)')"
    steps:
      - uses: actions/checkout@v4
      - uses: bufbuild/buf-setup-action@v1
      - name: "Generate OpenAPI spec"
        run: |
          cd protos
          buf generate
          cp openapi.yaml ../docs/.gitbook.yaml
      - name: "Generate API Reference Docs"
        run: |
          cd scripts/docs
          pip install pyyaml
          python gendocs.py
      - name: Commit changes
        uses: EndBug/add-and-commit@v9 # You can change this to use a specific version.
        with:
          # The arguments for the `git add` command (see the paragraph below for more info)
          # Default: '.'
          add: 'docs'

          # The name of the user that will be displayed as the author of the commit.
          # Default: depends on the default_author input
          author_name: docs-bot

          # Determines the way the action fills missing author name and email. Three options are available:
          # - github_actor -> UserName <UserName@users.noreply.github.com>
          # - user_info -> Your Display Name <your-actual@email.com>
          # - github_actions -> github-actions <email associated with the github logo>
          # Default: github_actor
          default_author: github_actor

          # Arguments for the git fetch command. If set to false, the action won't fetch the repo.
          # For more info as to why fetching is usually recommended, please see the "Performance on large repos" FAQ.
          # Default: --tags --force
          fetch: false

          # The message for the commit.
          # Default: 'Commit from GitHub Actions (name of the workflow)'
#          message: 'Your commit message'