name: Docs

on:
  push:
    branches:
      - main
      - alpha
      - beta

jobs:
  publish_docs:
    runs-on: ubuntu-latest
    if: "contains(github.event.head_commit.message, 'chore(release)')"
    steps:
      - uses: actions/checkout@v4
      - uses: bufbuild/buf-setup-action@v1
      - name: "Generate Proto Filedescriptor"
        # Normally generated in the Gradle prepareForDocker step, but the ciBuild flag disables that
        run: |
          cd protos
          mkdir -p ../app/build/docker
          buf build -o ../app/build/docker/descriptor.binpb
      - run: ./gradlew prepareForDocker -PciBuild
      # This should be done in the docs workflow
      - name: "Generate OpenAPI spec"
        run: |
          cd protos
          buf generate
          cp gen/openapi.yaml ../docs/.gitbook.yaml
      - name: "Generate API Reference Docs"
        run: |
          cd scripts/docs
          pip install pyyaml
          python generate.py
