name: Pull Request Build

on:
  push:
    branches-ignore:
      - "main"
      - "alpha"
      - "beta"
    paths-ignore:
      - "docs/**"

jobs:
  pr-build:
    runs-on: ubuntu-latest
    # based on: https://docs.github.com/en/actions/using-containerized-services/creating-postgresql-service-containers#running-jobs-directly-on-the-runner-machine
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: postgres
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
      # pace database for integration test
      postgres_pace:
        image: postgres
        env:
          POSTGRES_USER: pace
          POSTGRES_PASSWORD: pace
          PGDATA: /data/postgres
        options: >-
          --health-cmd pg_isready
        ports:
          - "5433:5432"
      # public.demo database for integration test
      postgres_processing_platform:
        image: postgres
        env:
          POSTGRES_USER: standalone
          POSTGRES_PASSWORD: standalone
          POSTGRES_DB: standalone
          PGDATA: /data/postgres
        options: >-
          --health-cmd pg_isready
        ports:
          - "5431:5432"
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
      - name: install postgresql-client
        run: sudo apt update -y && sudo apt install -y postgresql-client
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      - name: Execute Gradle build
        run: ./gradlew build -PciBuild
      - name: copy app.jar to integration-test directory
        run: cp server/build/libs/app.jar integration-test/
      - name: executing integration test
        id: integration-test
        working-directory: integration-test/
        run: |
          chmod go-rw pgpass
          make pace all kill-pace
      - name: print PACE logs
        if: always() && steps.integration-test.outcome == 'failure'
        working-directory: integration-test/
        run: |
          cat pace.log
