name: Pull Request Build

on:
  push:
    branches-ignore:
      - "main"
      - "alpha"
      - "beta"
    paths-ignore:
      - "docs/**"

jobs:
  pr-build:
    runs-on: ubuntu-latest
    # based on: https://docs.github.com/en/actions/using-containerized-services/creating-postgresql-service-containers#running-jobs-directly-on-the-runner-machine
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: postgres
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
      postgres_pace:
        image: postgres
        env:
          POSTGRES_USER: pace
          POSTGRES_PASSWORD: pace
          PGDATA: /data/postgres
        options: >-
          --health-cmd pg_isready
        ports:
          - "5433:5432"
      postgres_processing_platform:
        image: postgres
        env:
          POSTGRES_USER: standalone
          POSTGRES_PASSWORD: standalone
          POSTGRES_DB: standalone
          PGDATA: /data/postgres
        options: >-
          --health-cmd pg_isready
        volumes:
          - ./data.sql:/docker-entrypoint-initdb.d/data.sql
        ports:
          - "5431:5432"
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      - name: Execute Gradle build
        run: ./gradlew build -PciBuild
      - name: copy app.jar
        run: cp app/build/libs/app.jar integration-test/
      - name: install postgresql-client
        run: sudo apt update -y && sudo apt install -y postgresql-client
      - name: all steps
        working-directory: integration-test/
        run: |
          ./wait-for-port.sh 5431
          make all
